
 
name: Demo workflow

on: 
 pull_request:
   branches: ["master"]
 workflow_dispatch:
 
jobs: 
 runOnPullRequest:
  runs-on: self-hosted
  steps:
   - uses: actions/checkout@v1
   - name: Running command on PR
     run: mvn clean test
   
