
 
name: Demo workflow

on: 
 pull_request:
   branches: ["master"]
 workflow_dispatch:
 
jobs: 
 runOnPullRequest:
  runs-on: self-hosted
  steps:
   - uses: actions/checkout@v1
   - name: Running command on PR
     run: mvn clean test
   - name: Dump GitHub event
     run: echo '${{ toJSON(github.event) }}'
   - name: Dump GitHub pull_request
     run: echo '${{ toJSON(github.event.pull_request) }}'
   - name: Dump GitHub title
     run: echo ${{toJSON(github.event.pull_request.title)}}
   - name: Dump GitHub context
     run: echo '${{ toJSON(github) }}'
   - name: Dump job context
     run: echo '${{ toJSON(job) }}'
   - name: Dump steps context
     run: echo '${{ toJSON(steps) }}'
   - name: Dump runner context
     run: echo '${{ toJSON(runner) }}'
   - name: Dump strategy context
     run: echo '${{ toJSON(strategy) }}'
   - name: Dump matrix context
     run: echo '${{ toJSON(matrix) }}'
   - name: Storing PR title
     run: |
      set prTitle=${{toJSON(github.event.pull_request.title)}}
      FOR /f "delims=:" %a IN ("%prTitle%") do set testCases=%a
      echo %testCases%
 
